### ISSUE TITLE
Firebird 4 and local protocol on Linux

### ISSUE THREAD

**Issue by sdnetwork** [mrotteveel/jaybird-fbclient#1]
Hello,

do you know if it works on firebird 4 on linux with local protocol ?

i obtain strange behaviour :

1) sometime it segfault
2) I need to be root otherwise i get (operating system directive access failed; 20 [SQLState:HY000, ISC error code:335544373]), but it works with native protocol.

this is my jdbc url : jdbc:firebirdsql:local:/test/db/test.fdb

more over, for sure to understand well the local protocol, can you confirm me that it needs a server (not like embed) ?
because it can connect without server with this url  jdbc:firebirdsql:local:/test/db/test.fdb

Thx in advance.

**Comment by mrotteveel** [comment]
Unfortunately, the local protocol will likely (try to) use Firebird Embedded since Firebird 3.0. See also [Firebird 3.0 Release Notes, section Connection String and Protocols](https://www.firebirdsql.org/file/documentation/release_notes/html/en/3_0/rlsnotes30.html#rnfb30-engine-modes-protocols): 

> Local connection is implied if <host> is omitted. Depending on settings, platform and Firebird version, it could be performed via either the embedded engine, XNET (shared memory) protocol or TCP/IP localhost loopback.

You might get it to work by specifying connection property `config` with value `Providers = Loopback`, but I'm not really sure if that works. 

As far as I'm aware on Linux, Firebird never used IPC (that is only available on Windows, using XNET), but would create a TCP/IP connection to localhost if only a path was specified and a client without embedded engine was used. So the same effect would be achieved by using a native connection with an explicit host name `localhost`.

However, I'd recommend using the normal pure-java protocol instead of any of the native/local/embedded protocols. 

As to the first error you mention, I would need to have more information to be able to diagnose that. As to the second error, that is because Embedded is used and you probably don't have sufficient access to some of the files and directories needed (database file, security database, lock files, etc).

**Comment by mrotteveel** [comment]
As an aside, this question would have been more suitable to ask on https://groups.google.com/g/firebird-java or otherwise on https://github.com/FirebirdSQL/jaybird
